---
- name: install unzip package
  yum: name=unzip

- name: install python-psycopg2 package
  yum: name=python-psycopg2

- name: create user pentaho
  user: name=pentaho state=present

- name: create Pentaho Home directory
  file: path=/opt/pentaho state=directory owner=pentaho group=pentaho

- name: verify if Pentaho BI Server was downloaded
  stat: path="/tmp/{{ bi_server_filename }}" get_checksum=yes
  register: bi_server_downloaded

- name: download Pentaho BI Server
  when: "not bi_server_downloaded.stat.exists or bi_server_downloaded.stat.checksum != '{{ bi_server_sha1_checksum }}'"
  get_url:
    url: '{{ bi_server_url }}'
    dest: '/tmp/{{ bi_server_filename }}'
    timeout: 60
    sha256sum: '{{ bi_server_sha256_checksum }}'

- name: unzip Pentaho BI Server
  unarchive:
    copy: no
    src: '/tmp/{{ bi_server_filename }}'
    dest: /opt/pentaho
    creates: /opt/pentaho/biserver-ce/start-pentaho.sh

- name: set group permissions to /opt/pentaho
  file: path=/opt/pentaho state=directory owner=pentaho group=pentaho recurse=yes

- name: copy postgresql scripts for hibernate, quartz and jackrabbit databases
  copy:
    src: '{{ item.src }}'
    dest: '/opt/pentaho/{{ item.dest }}'
    owner: pentaho
    group: pentaho
    mode: 0644
  notify: restart pentaho bi server
  with_items:
    - { src: 'scripts/create_quartz_postgresql.sql', dest: 'biserver-ce/data/postgresql/' }
    - { src: 'scripts/create_repository_postgresql.sql', dest: 'biserver-ce/data/postgresql/' }
    - { src: 'scripts/create_jcr_postgresql.sql', dest: 'biserver-ce/data/postgresql/' }

- name: list postgresql databases
  command: /usr/bin/psql -U postgres -p 5454 -l
  register: databases_list
  changed_when: no

- name: create hibernate, quartz and jackrabbit databases
  command: /usr/bin/psql -U postgres -p 5454 -f /opt/pentaho/biserver-ce/data/postgresql/{{ item.script }}
  when: "'{{ item.bdd }}' not in databases_list.stdout"
  with_items:
    - { script: 'create_repository_postgresql.sql', bdd: 'hibernate' }
    - { script: 'create_quartz_postgresql.sql', bdd: 'quartz' }
    - { script: 'create_jcr_postgresql.sql', bdd: 'jcr' }

- name: delete postgresql jdbc default driver
  file: path=/opt/pentaho/biserver-ce/tomcat/lib/postgresql-9.3-1102-jdbc4.jar state=absent

- name: copy postgresql-9.4 jdbc driver
  copy:
    src: jdbc/postgresql-9.4-1201.jdbc4.jar
    dest: /opt/pentaho/biserver-ce/tomcat/lib/
    owner: pentaho
    group: pentaho
    mode: 0644

- name: copy tomcat context file and deployment descriptor
  copy:
    src: '{{ item.src }}'
    dest: '/opt/pentaho/{{ item.dest }}'
    owner: pentaho
    group: pentaho
    mode: 0644
  notify: restart pentaho bi server
  with_items:
    - { src: 'configuration/context.xml', dest: 'biserver-ce/tomcat/webapps/pentaho/META-INF/' }
    - { src: 'configuration/web.xml', dest: 'biserver-ce/tomcat/webapps/pentaho/WEB-INF/' }

- name: copy bi-server configuration files
  copy:
    src: '{{ item.src }}'
    dest: '/opt/pentaho/{{ item.dest }}'
    owner: pentaho
    group: pentaho
    mode: 0644
  notify: restart pentaho bi server
  with_items:
    - { src: 'configuration/hibernate-settings.xml', dest: 'biserver-ce/pentaho-solutions/system/hibernate/' }
    - { src: 'configuration/postgresql.hibernate.cfg.xml', dest: 'biserver-ce/pentaho-solutions/system/hibernate/' }
    - { src: 'configuration/applicationContext-spring-security-hibernate.properties', dest: 'biserver-ce/pentaho-solutions/system/' }
    - { src: 'configuration/repository.xml', dest: 'biserver-ce/pentaho-solutions/system/jackrabbit/' }
    - { src: 'configuration/quartz.properties', dest: 'biserver-ce/pentaho-solutions/system/quartz/' }


- name: copy pentaho.service file
  copy:
    src: service/pentaho.service
    dest: /etc/systemd/system/
    owner: root
    group: root
    mode: 0644

- name: active pentaho daemon
  service: name=pentaho enabled=yes state=started

- meta: flush_handlers
