---
dependencies:
  - role: alexanderjardim.oracle_jdk
    oracle_jdk_version: '{{ version_jdk }}'
    oracle_jdk_download_dir: '~'
    oracle_jdk_package: jdk-8u60-linux-x64.tar.gz
    oracle_jdk_package_subdir: 8u60-b27
    oracle_jdk_installation_dir: '{{ installation_path }}'
